# Generated by Django 2.2.3 on 2019-09-13 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code_Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('python', models.TextField(max_length=300)),
                ('javascript', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=255)),
                ('img_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('str', 'String'), ('int', 'Integer'), ('float', 'Float')], default='int', max_length=5)),
                ('code_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Code_Block')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Resource')),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Code_Block')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Resource')),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('NO', 'Node'), ('BL', 'Block')], default='NO', max_length=2)),
                ('code_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Code_Block')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Resource')),
            ],
        ),
        migrations.CreateModel(
            name='Data_Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('methods', models.ManyToManyField(to='main_app.Method')),
                ('properties', models.ManyToManyField(to='main_app.Property')),
            ],
        ),
    ]
