# Generated by Django 2.2.3 on 2019-09-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20190913_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('str', 'String'), ('int', 'Integer'), ('float', 'Float'), ('sca', 'Scalar')], default='int', max_length=5),
        ),
    ]
