# Generated by Django 2.2.3 on 2019-09-13 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20190913_2257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code_block',
            options={'verbose_name': 'Code Block'},
        ),
        migrations.AlterModelOptions(
            name='data_structure',
            options={'verbose_name': 'Data Structure'},
        ),
    ]
