# Generated by Django 2.2.5 on 2019-09-19 21:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0009_auto_20190914_0052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data_Structure',
            new_name='DataStructure',
        ),
    ]
