# Generated by Django 2.2.5 on 2019-09-19 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20190919_2158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Code_Block',
            new_name='CodeBlock',
        ),
    ]
