# Generated by Django 2.2.5 on 2019-11-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20190919_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeblock',
            name='javascript',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='codeblock',
            name='python',
            field=models.TextField(max_length=1000),
        ),
    ]
